In [1]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [3]:
import numpy as np #operasi numerik

import nltk #pengolahan text

import string #manipulasi text

import re #mencari pola kata yang spesifik

import warnings #menghilangkan warning karena migrasi python
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [7]:
df = pd.read_csv('DataSetM-Pajak.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,1,2026-05-31 15:06:05,"parah aplikasi apaan begini,masa Eror Mulu hadeeeh"
1,Pengguna Google,2,2026-05-31 13:26:18,🙏kartu WNWP Ari Iswanto kok gak idup lagi ya
2,Pengguna Google,1,2026-05-31 12:57:31,"Mau log in via aplikasi diarahin ke web coretax wkwkw. udah gitu gabisa di akses 😂. ""SITUS TIDAK DAPAT DIJANGKAU"". Lucu ya aplikasi pelayanan untuk masyarakat seburuk ini. 👎🏻"
3,Pengguna Google,1,2026-05-31 10:51:00,ribet
4,Pengguna Google,5,2026-05-31 00:41:31,Oke good

In [8]:
df['sentiment'] = df['score'].map({1.0:0, 2.0:0, 3.0:1, 4.0:1, 5.0:1})

In [9]:
myData = pd.DataFrame(df[['content', 'sentiment']])
myData.head(10)

,content,sentiment
0,"parah aplikasi apaan begini,masa Eror Mulu hadeeeh",0
1,🙏kartu WNWP Ari Iswanto kok gak idup lagi ya,0
2,"Mau log in via aplikasi diarahin ke web coretax wkwkw. udah gitu gabisa di akses 😂. ""SITUS TIDAK DAPAT DIJANGKAU"". Lucu ya aplikasi pelayanan untuk masyarakat seburuk ini. 👎🏻",0
3,ribet,0
4,Oke good,1
5,"aplikasi setan ini ,semua aplikasi buatan negara gaada yang bener otak karupsii semua",0
6,Rata-rata apk pemerintah di konoha sampah semua👊😬,0
7,"susah betul daftar coretex nyaa, malah tambah rumit sekarang jdi malas lapor² pajak, 3 jam bolak balik aja",0
8,aplikasi ribet rencana biar simpel tapi priteksinya seperti aplikasi menyimpan uang milyaran mau masuk lupa email nggak bisa diperbaiki,0
9,ngabisin anggaran negara doang... kek sengaja dibuat susah biar banyakan yang kena denda... cuma mau bayar pajak/ngurus SPT doang aja dipersulit... percuma kebanyakan marketing hasilnya nihil,0

In [10]:
my_df = myData[['content', 'sentiment']]

In [11]:
my_df.to_csv('label_mpajak.csv', index=False)