In [2]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install nltk
!pip install sastrawi

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [4]:
import numpy as np
import nltk
import string
import re
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [16]:
df = pd.read_csv('Label_pajak.csv')

In [17]:
df['content'] = df['content'].apply(lambda x: " ".join(x.lower() for x in x.split()))
df.head()

,content,sentiment
0,"parah aplikasi apaan begini,masa eror mulu hadeeeh",0
1,🙏kartu wnwp ari iswanto kok gak idup lagi ya,0
2,"mau log in via aplikasi diarahin ke web coretax wkwkw. udah gitu gabisa di akses 😂. ""situs tidak dapat dijangkau"". lucu ya aplikasi pelayanan untuk masyarakat seburuk ini. 👎🏻",0
3,ribet,0
4,oke good,1

In [18]:
df['content'] = df['content'].str.replace(r'[^\x00-\x7F]+', '', regex=True)

df.head(30)

,content,sentiment
0,"parah aplikasi apaan begini,masa eror mulu hadeeeh",0
1,kartu wnwp ari iswanto kok gak idup lagi ya,0
2,"mau log in via aplikasi diarahin ke web coretax wkwkw. udah gitu gabisa di akses . ""situs tidak dapat dijangkau"". lucu ya aplikasi pelayanan untuk masyarakat seburuk ini.",0
3,ribet,0
4,oke good,1
5,"aplikasi setan ini ,semua aplikasi buatan negara gaada yang bener otak karupsii semua",0
6,rata-rata apk pemerintah di konoha sampah semua,0
7,"susah betul daftar coretex nyaa, malah tambah rumit sekarang jdi malas lapor pajak, 3 jam bolak balik aja",0
8,aplikasi ribet rencana biar simpel tapi priteksinya seperti aplikasi menyimpan uang milyaran mau masuk lupa email nggak bisa diperbaiki,0
9,ngabisin anggaran negara doang... kek sengaja dibuat susah biar banyakan yang kena denda... cuma mau bayar pajak/ngurus spt doang aja dipersulit... percuma kebanyakan marketing hasilnya nihil,0
10,kenapa harus pake pulsa pas ngirim kode otp nomor telpon ga sekalian aja apa pake duit 1juta gitu? udah mah penting tapi malah di bikin susah mau kerja harus punya npwp definisi udah cari kerja susah ngerjain kaya ginian juga susah apa lagi yang harus susah coba? belom lagi bikin yang lain juga lama prosesnya bolak balik juga hedeh,0
11,"daftar efin aja susahnya minta ampun, di indo sesusah ini anjir apa padahal pake duit sendiri tapi susah bgtt",0
12,jalankan demi masa yang akan datang,1
13,poto berulang ulang...kok gagal terus sih.....tolong perbaiki....,1
14,percuma pake aplikasi ini,0
15,apl gak guna,0
16,jelek nyaa banyak bug sama error engga jelas kaya di webnya,0
17,"aplikasi ter stress, coba siapapun yg bikin aplikasi nya dibenahi lagi!! btl2 gajelas bgtt ntah itu di web di aplikasi gaje bgtt, plenger final",0
18,ngabisin anggaran doang bkin website kek kntlll,0
19,gak guna sangat ribet. lebih nyaman pake e feling tapi cuma nyampe tahun 2024 taik lah sistem pajak,0
20,"payah banget, login susah, sekalinya masuk, logout sendiri..",0
21,20min 9,0
22,kartu npwpnya ga ada,0
23,"aplikasi error terus...habis download malah masuk lagi ke browser..terus buat apa ada aplikasi nya...kalau bikin aplikasi mikir dulu, masa kalian di gaji pakai uang hasil keringat rakyat, kerja bikin aplikasi aja di persulit atau dipersusah tanpa adanya solusi...selamat atas bertambah nya dosa kalian",0
24,"input pasword, captha dan id udah bener dianggap salah pasword dan mesti reset pasword giliran udah reset trus log in pasword udah bener, id bener, captcha bener pas log in malah langsung error aplikasi nya lol",0
25,"aku sudah pilih jenis pekerjaan tapi pas diverifikasi gaa bisa, gj banget",1
26,"aplikasi biar ada aja, tolooool",0
27,"payah masa error 400 padahal jaringan baik, payah, sertifikat aktif, di aktivasi malah out.",0
28,gabisa masuk trs padahal pasword sama nomor npwp udah bner,0
29,busuk,0

In [22]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords_id = factory.get_stop_words()

def remove_stopwords(text):
  """custom function to remove the stopwords"""
  return " ".join([word for word in str(text).split() if word not in stopwords_id])

df['content'] = df['content'].apply(lambda text:remove_stopwords(text))
df.head()

,content,sentiment
0,"parah aplikasi apaan begini,masa eror mulu hadeeeh",0
1,kartu wnwp ari iswanto kok gak idup,0
2,"mau log in via aplikasi diarahin web coretax wkwkw. udah gitu gabisa akses . ""situs dijangkau"". lucu aplikasi pelayanan masyarakat seburuk ini.",0
3,ribet,0
4,oke good,1

In [23]:
from Sastrawi.Stemmer.Stemmer import Stemmer

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
Stemmer_id = factory.create_stemmer()

def stem_words(text):
  return " ".join([Stemmer_id.stem(word) for word in text.split()])

df['content'] = df['content'].apply(lambda text:stem_words(text))
df.head()

,content,sentiment
0,parah aplikasi apa begini masa eror mulu hadeeeh,0
1,kartu wnwp ari iswanto kok gak idup,0
2,mau log in via aplikasi diarahin web coretax wkwkw udah gitu gabisa akses situs jangkau lucu aplikasi layan masyarakat buruk ini,0
3,ribet,0
4,oke good,1

In [24]:
def tokenize_text(text):
  tokenized_text = text.split()
  return tokenized_text
df['content'] = df['content'].apply(lambda x: tokenize_text(x))
df.head()

,content,sentiment
0,"[parah, aplikasi, apa, begini, masa, eror, mulu, hadeeeh]",0
1,"[kartu, wnwp, ari, iswanto, kok, gak, idup]",0
2,"[mau, log, in, via, aplikasi, diarahin, web, coretax, wkwkw, udah, gitu, gabisa, akses, situs, jangkau, lucu, aplikasi, layan, masyarakat, buruk, ini]",0
3,[ribet],0
4,"[oke, good]",1

In [26]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
def lemmatize_text(token_list):
  return " ".join([lemmatizer.lemmatize(token) for token in token_list if not token in set()])

lemmatizer = nltk.stem.WordNetLemmatizer()
df['content'] = df['content'].apply(lambda x: lemmatize_text(x))
df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

,content,sentiment
0,parah aplikasi apa begini masa eror mulu hadeeeh,0
1,kartu wnwp ari iswanto kok gak idup,0
2,mau log in via aplikasi diarahin web coretax wkwkw udah gitu gabisa akses situs jangkau lucu aplikasi layan masyarakat buruk ini,0
3,ribet,0
4,oke good,1

In [27]:
my_df = df[['content', 'sentiment']]

In [28]:
my_df.to_csv('bersih_mpajak.csv', index=False)